;; init.el --- Just loading the real thing
;; Fuck the bell sound
(setq ring-bell-function 'ignore)
;; Load up Org Mode and Babel
;; and load the configuration file
(setq dotfiles-dir (file-name-directory (or load-file-name (buffer-file-name))))
(add-to-list 'load-path
	     (expand-file-name "lisp" (expand-file-name "org" (expand-file-name "src" dotfiles-dir))))
(require 'org-install)
(org-babel-load-file (expand-file-name "config.org" dotfiles-dir))

;; ------------------------ Generated By Emacs ----------------------------------
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(delete-selection-mode nil)
 '(package-selected-packages
   (quote
    (python-mode go-mode go-snippets web-mode emmet-mode yasnippet-snippets yasnippet company-lsp lsp-ui lsp-mode flycheck company elfeed org-re-reveal doom-themes ibuffer-sidebar hide-mode-line doom-modeline dashboard use-package))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
